openapi: 3.0.0
info:
  title: Easyappz Messenger API
  version: 1.0.0
  description: REST API for secure client-side encrypted messenger
servers:
  - url: /
paths:
  /api/auth/register:
    post:
      summary: Register by phone and password
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [phone, password]
              properties:
                phone:
                  type: string
                  maxLength: 32
                password:
                  type: string
                  minLength: 6
                first_name:
                  type: string
                last_name:
                  type: string
      responses:
        '201':
          description: Registered
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthResponse'
        '400':
          description: Bad request
  /api/auth/login:
    post:
      summary: Login by phone and password
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [phone, password]
              properties:
                phone:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: Logged in
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthResponse'
        '400':
          description: Invalid credentials
  /api/users/me:
    get:
      summary: Get current user profile
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Current profile
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Profile'
        '404':
          description: Profile not found
    patch:
      summary: Update current user names (first_name, last_name only)
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                first_name:
                  type: string
                last_name:
                  type: string
      responses:
        '200':
          description: Updated profile
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Profile'
        '400':
          description: Validation error
  /api/users/search:
    get:
      summary: Search users by phone (icontains)
      security:
        - bearerAuth: []
      parameters:
        - in: query
          name: phone
          schema:
            type: string
          required: true
          description: Phone substring to search
      responses:
        '200':
          description: List of public users
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PublicUser'
        '400':
          description: Missing phone param
  /api/dialogs/:
    get:
      summary: List current user's dialogs
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Array of dialogs
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Dialog'
    post:
      summary: Create or return dialog with specified user
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [user_id]
              properties:
                user_id:
                  type: integer
      responses:
        '201':
          description: Dialog created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Dialog'
        '200':
          description: Dialog already exists
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Dialog'
        '400':
          description: Invalid request (e.g., self-dialog)
        '404':
          description: User not found
  /api/dialogs/{id}/:
    get:
      summary: Get dialog by id (only for its participants)
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Dialog object
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Dialog'
        '403':
          description: Forbidden
        '404':
          description: Not found
  /api/dialogs/{id}/messages:
    get:
      summary: List messages in dialog
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
        - in: query
          name: limit
          required: false
          schema:
            type: integer
            default: 50
        - in: query
          name: offset
          required: false
          schema:
            type: integer
            default: 0
        - in: query
          name: after
          required: false
          schema:
            type: string
            format: date-time
          description: Return messages created strictly after this timestamp
      responses:
        '200':
          description: Paginated list of messages
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MessagesListResponse'
        '400':
          description: Bad params
        '403':
          description: Forbidden
        '404':
          description: Dialog not found
    post:
      summary: Create message in dialog
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [ciphertext]
              properties:
                ciphertext:
                  type: string
      responses:
        '201':
          description: Created message
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Message'
        '400':
          description: Validation error
        '403':
          description: Forbidden
        '404':
          description: Dialog not found
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    Profile:
      type: object
      properties:
        id:
          type: integer
        phone:
          type: string
        first_name:
          type: string
        last_name:
          type: string
      required: [id, phone]
    PublicUser:
      type: object
      properties:
        id:
          type: integer
        phone:
          type: string
        first_name:
          type: string
        last_name:
          type: string
      required: [id, phone]
    Dialog:
      type: object
      properties:
        id:
          type: integer
        participant:
          $ref: '#/components/schemas/PublicUser'
        created_at:
          type: string
          format: date-time
        last_message:
          oneOf:
            - $ref: '#/components/schemas/LastMessage'
            - type: 'null'
      required: [id, participant, created_at]
    LastMessage:
      type: object
      properties:
        ciphertext:
          type: string
        created_at:
          type: string
          format: date-time
      required: [ciphertext, created_at]
    Message:
      type: object
      properties:
        id:
          type: integer
        dialog:
          type: integer
        sender:
          type: integer
        ciphertext:
          type: string
        created_at:
          type: string
          format: date-time
      required: [id, dialog, sender, ciphertext, created_at]
    MessagesListResponse:
      type: object
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/Message'
        total:
          type: integer
        limit:
          type: integer
        offset:
          type: integer
      required: [items, total, limit, offset]
